services:
  # proxy:
  #   container_name: ProxyServer-que
  #   image: nginx
  #   volumes:
  #     - type: bind
  #       source: ./proxy/nginx.conf
  #       target: /etc/nginx/conf.d/default.conf
  #       read_only: true
  #   ports:
  #     - 88:80
  #   network_mode: host

  database:
    container_name: postgres-que
    image: postgres:15.4
    ports:
      - 5456:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgresSQL2023*
      POSTGRES_DB: queez
      POSTGRES_PORT: 5432

  # docker compose up -d
